name: "House Plant Care"
description: "Track and manage your house plant care schedules with alerts and overdue notifications"
version: "1.0.0"
slug: "house_plant_care"
init: false
arch:
  - amd64
startup: application
ingress: true
ingress_port: 3000
ingress_stream: true
panel_icon: mdi:flower
panel_title: Plant Care
map:
  - data:rw
options:
  session_password: ""
  trefle_api_token: ""
schema:
  session_password: password
  trefle_api_token: password?
image: "gitea.home.arpa/jhonny/house-plant-care-{arch}"